services:
  - type: web
    name: fastapi-predict-car
    runtime: python
    pythonVersion: 3.12.7
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: "generated_secret_key"
      - key: DATABASE_URL
        value: "mysql+pymysql://babaste:Simplon@mysql-babaste.alwaysdata.net:3306/babaste_predict_car"
      - key: ENV
        value: "production"
    healthCheckPath: /health
    autoDeploy: true
    plan: free